---
- name: Apply fundamental operating system baselines
  hosts: all
  become: yes
  roles:
    - common

- name: Isolate and establish backend database infrastructure
  hosts: db
  become: yes
  roles:
    - db

- name: Deploy application platform runtime and frontend gateway proxy
  hosts: workers
  become: yes
  roles:
    - worker